In [8]:
!pip install -q pandas numpy matplotlib scikit-learn


[notice] A new release of pip is available: 24.0 -> 24.3.1
[notice] To update, run: pip install --upgrade pip


In [9]:
print("b")

b


In [10]:
print("c")

c


In [11]:
import copy
import os
import pickle

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.manifold import TSNE
from sklearn.manifold import Isomap
from sklearn.decomposition import PCA

In [12]:
print("Current working directory: {0}".format(os.getcwd()))
os.chdir('../../sound-spaces')
print("Current working directory: {0}".format(os.getcwd()))

Current working directory: /home/4/ud02274/navigation/myss/sound-spaces/scripts
Current working directory: /home/4/ud02274/navigation/myss/sound-spaces


In [16]:
def read_data(file_name):

    with open(file_name, 'r') as f:
        word2vector = {}
        for line in f:
            vals = line.rstrip().split(' ')
            word2vector[vals[0]] = [float(x) for x in vals[1:]]
    print("Total Words in DataSet:", len(word2vector))

    return word2vector

pre_trained_word_vectors_path = r"./data/glove_data/glove.840B.300d.txt"
w2v = read_data(pre_trained_word_vectors_path)

Total Words in DataSet: 2196016


In [17]:
# embedding = Isomap(n_neighbors=5, n_components=2)
# embedding = PCA(n_components=2)
embedding = TSNE(n_components=2, random_state=0, perplexity=20)

In [18]:
objects_of_interest = ['bathtub', 'bed', 'cabinet', 'chair', 'drawers', 'clothes', 'counter', 'cushion',
                       'fireplace', 'gym', 'picture', 'plant', 'seating', 'shower', 'sink', 'sofa', 'stool',
                       'table', 'toilet', 'towel', 'tv']
# chest_of_drawers > drawers
# gym_equipment > gym
# tv_monitor > tv

words = objects_of_interest
vectors = np.array([w2v[word] for word in words])

f = open("debug.txt", "a")
f.write(f"objects\n")
f.write(f"shape of vectors: {np.shape(vectors)}\n")
f.close()

Y = embedding.fit_transform(vectors[:1000])

plt.scatter(Y[:, 0], Y[:, 1])
for word, x, y in zip(words, Y[:, 0], Y[:, 1]):
    if word == 'drawers':
        word = 'chest_of_drawers'
    elif word == 'gym':
        word = 'gym_equipment'
    elif word == 'tv':
        word = 'tv_monitor'
    # for handling object and region of same name
    elif word == 'toilet':
        word = 'toilet_object'
        
    plt.annotate(word, xy=(x, y), xytext=(0, 0), textcoords="offset points")
plt.savefig(r"data/glove_data/objects_embeddings.png", bbox_inches='tight', dpi=100)
plt.close()

objects_vector = {}
for word in words:
    if word == 'drawers':
        objects_vector['chest_of_drawers'] = w2v[word]
    elif word == 'gym':
        objects_vector['gym_equipment'] = w2v[word]
    elif word == 'tv':
        objects_vector['tv_monitor'] = w2v[word]
    # for handling object and region of same name
    elif word == 'toilet':
        objects_vector['toilet_object'] = w2v[word]
    else:
        objects_vector[word] = w2v[word]

In [19]:
regions_of_interest = ['balcony', 'bathroom', 'bedroom', 'closet', 'diningroom', 'foyer', 'familyroom', 'hallway',
                       'junk', 'kitchen', 'laundryroom', 'livingroom', 'lounge', 'meeting', 'office',
                       'room', 'outdoor', 'porch', 'game', 'spa', 'stairs', 'toilet', 'toolroom',
                       'workout']
# dining room > diningroom
# entryway/foyer/lobby > foyer
# familyroom/lounge > familyroom
# laundryroom/mudroom > laundryroom
# living room > livingroom
# meetingroom/conferenceroom > meeting
# other room > room
# porch/terrace/deck > porch
# rec/game > game
# spa/sauna > spa
# utilityroom/toolroom > toolroom
# workout/gym/exercise > workout

words = regions_of_interest
vectors = np.array([w2v[word] for word in words])
f = open("debug.txt", "a")
f.write(f"regions\n")
f.write(f"shape of vectors: {np.shape(vectors)}\n")
f.close()
Y = embedding.fit_transform(vectors[:1000])

plt.scatter(Y[:, 0], Y[:, 1])
for word, x, y in zip(words, Y[:, 0], Y[:, 1]):
    if word == 'diningroom':
        word = 'dining room'
    elif word == 'foyer':
        word = 'entryway/foyer/lobby'
    elif word == 'familyroom':
        word = 'familyroom/lounge'
    elif word == 'laundryroom':
        word = 'laundryroom/mudroom'
    elif word == 'livingroom':
        word = 'living room'
    elif word == 'meeting':
        word = 'meetingroom/conferenceroom'
    elif word == 'room':
        word = 'other room'
    elif word == 'porch':
        word = 'porch/terrace/deck'
    elif word == 'game':
        word = 'rec/game'
    elif word == 'spa':
        word = 'spa/sauna'
    elif word == 'toolroom':
        word = 'utilityroom/toolroom'
    elif word == 'workout':
        word = 'workout/gym/exercise'
    # for handling object and region of same name
    elif word == 'toilet':
        word = 'toilet_region'

    plt.annotate(word, xy=(x, y), xytext=(0, 0), textcoords="offset points")
plt.savefig(r"data/glove_data/regions_embeddings.png", bbox_inches='tight', dpi=100)
plt.close()

regions_vector = {}
for word in words:
    if word == 'diningroom':
        regions_vector['dining room'] = w2v[word]
    elif word == 'foyer':
        regions_vector['entryway/foyer/lobby'] = w2v[word]
    elif word == 'familyroom':
        regions_vector['familyroom/lounge'] = w2v[word]
    elif word == 'laundryroom':
        regions_vector['laundryroom/mudroom'] = w2v[word]
    elif word == 'livingroom':
        regions_vector['living room'] = w2v[word]
    elif word == 'meeting':
        regions_vector['meetingroom/conferenceroom'] = w2v[word]
    elif word == 'room':
        regions_vector['other room'] = w2v[word]
    elif word == 'porch':
        regions_vector['porch/terrace/deck'] = w2v[word]
    elif word == 'game':
        regions_vector['rec/game'] = w2v[word]
    elif word == 'spa':
        regions_vector['spa/sauna'] = w2v[word]
    elif word == 'toolroom':
        regions_vector['utilityroom/toolroom'] = w2v[word]
    elif word == 'workout':
        regions_vector['workout/gym/exercise'] = w2v[word]
    # for handling object and region of same name
    elif word == 'toilet':
        regions_vector['toilet_region'] = w2v[word]
    else:
        regions_vector[word] = w2v[word]

embeddings_path = r"data/glove_data/glove_embeddings_300d.bin"
with open(embeddings_path, 'wb') as fo:
    pickle.dump(objects_vector, fo)
    pickle.dump(regions_vector, fo)

In [20]:
words = objects_of_interest + regions_of_interest
vectors = np.array([w2v[word] for word in words])

f = open("debug.txt", "a")
f.write(f"objects and regions\n")
f.write(f"shape of vectors: {np.shape(vectors)}\n")
f.close()

Y = embedding.fit_transform(vectors[:1000])

plt.scatter(Y[:, 0], Y[:, 1])
for label, x, y in zip(words, Y[:, 0], Y[:, 1]):
    plt.annotate(label, xy=(x, y), xytext=(0, 0), textcoords="offset points")
plt.savefig(r"data/glove_data/objects_regions_embeddings.png", bbox_inches='tight', dpi=100)
plt.close()

In [21]:
plt.figure(figsize=(15, 15))

i = 0
for word in words:
    
    color = 'r'
    if i >= len(objects_of_interest):
        color = 'b'
        
    plt.scatter(Y[i][0], Y[i][1], c=color, edgecolor='k', s=100, label=word)
    plt.annotate(
        word,
        xy=(Y[i][0], Y[i][1]),
        xytext=(-14, 14),
        textcoords='offset points',
        bbox=dict(boxstyle='round,pad=0.5', fc='yellow', alpha=0.5),
        arrowprops=dict(arrowstyle = '->', connectionstyle='arc3,rad=0')
    )
    
    i += 1

legend_elements = []
legend_elements.append(plt.Rectangle((0, 0), 1, 1, color='r', label="Objects"))
legend_elements.append(plt.Rectangle((0, 0), 1, 1, color='b', label="Regions"))
plt.legend(handles=legend_elements, fontsize=11, bbox_to_anchor=(1, 1))
plt.axis('equal')
if isinstance(embedding, Isomap):
    plt.savefig(r"data/glove_data/2D_objects_regions_embeddings_Isomap.png", bbox_inches='tight', dpi=100)
elif isinstance(embedding, PCA):
    plt.savefig(r"data/glove_data/2D_objects_regions_embeddings_PCA.png", bbox_inches='tight', dpi=100)
elif isinstance(embedding, TSNE):
    plt.savefig(r"data/glove_data/2D_objects_regions_embeddings_TSNE.png", bbox_inches='tight', dpi=100)
plt.close()

In [22]:
embeddings_path = r"data/glove_data/glove_embeddings_300d.bin"

bin_file = open(embeddings_path, "rb")
objects_vector = pickle.load(bin_file)
regions_vector = pickle.load(bin_file)
bin_file.close()

objects = list(sorted(objects_vector.keys()))
regions = list(sorted(regions_vector.keys()))

words = objects + regions

print("objects: ", len(objects), objects)
print("regions: ", len(regions), regions)
print("words: ", len(words), words)

objects:  21 ['bathtub', 'bed', 'cabinet', 'chair', 'chest_of_drawers', 'clothes', 'counter', 'cushion', 'fireplace', 'gym_equipment', 'picture', 'plant', 'seating', 'shower', 'sink', 'sofa', 'stool', 'table', 'toilet_object', 'towel', 'tv_monitor']
regions:  24 ['balcony', 'bathroom', 'bedroom', 'closet', 'dining room', 'entryway/foyer/lobby', 'familyroom/lounge', 'hallway', 'junk', 'kitchen', 'laundryroom/mudroom', 'living room', 'lounge', 'meetingroom/conferenceroom', 'office', 'other room', 'outdoor', 'porch/terrace/deck', 'rec/game', 'spa/sauna', 'stairs', 'toilet_region', 'utilityroom/toolroom', 'workout/gym/exercise']
words:  45 ['bathtub', 'bed', 'cabinet', 'chair', 'chest_of_drawers', 'clothes', 'counter', 'cushion', 'fireplace', 'gym_equipment', 'picture', 'plant', 'seating', 'shower', 'sink', 'sofa', 'stool', 'table', 'toilet_object', 'towel', 'tv_monitor', 'balcony', 'bathroom', 'bedroom', 'closet', 'dining room', 'entryway/foyer/lobby', 'familyroom/lounge', 'hallway', 'jun

In [23]:
wordsXwords = {}

word_row = {}
for word in words:
    if word not in word_row:
        word_row[word] = 0.0
    else:
        print("Word already exists: ", word)

for word in word_row:
    wordsXwords.setdefault(word, copy.deepcopy(word_row))

print("wordsXwords: ", len(wordsXwords))

wordsXwords:  45


In [24]:
graph_filename = r"data/metadata/mp3d_graph_object.csv"
df = pd.read_csv(graph_filename, delimiter=',')

for index, row in df.iterrows():
    object_row = row['Sounding Objects']
    if object_row == 'toilet':
        object_row = 'toilet_object'

    objects_row = row['Objects']
    objects_row = [obj.strip() for obj in objects_row.split(',')]
    if 'toilet' in objects_row:
        objects_row.remove('toilet')
        objects_row.append('toilet_object')
        
    regions_row = row['Regions']
    regions_row = [reg.strip() for reg in regions_row.split(',')]
    if 'toilet' in regions_row:
        regions_row.remove('toilet')
        regions_row.append('toilet_region')
    
    words_row = objects_row + regions_row
    
    for word in wordsXwords[object_row]:
        if word in words_row:
            wordsXwords[object_row][word] = 1

In [25]:
graph_filename = r"data/metadata/mp3d_graph_region.csv"
df = pd.read_csv(graph_filename, delimiter=',')

for index, row in df.iterrows():
    region_row = row['Regions']
    if region_row == 'toilet':
        region_row = 'toilet_region'

    objects_row = row['Objects']
    objects_row = [obj.strip() for obj in objects_row.split(',')]
    if 'toilet' in objects_row:
        objects_row.remove('toilet')
        objects_row.append('toilet_object')
        
    regions_row = row['Other Regions']
    regions_row = [reg.strip() for reg in regions_row.split(',')]
    if 'toilet' in regions_row:
        regions_row.remove('toilet')
        regions_row.append('toilet_region')
    
    words_row = objects_row + regions_row
    
    for word in wordsXwords[region_row]:
        if word in words_row:
            wordsXwords[region_row][word] = 1

In [26]:
wordsXwords_df = pd.DataFrame(wordsXwords).T
wordsXwords_df.to_csv(r"data/glove_data/adjmat.csv")

adjmat = wordsXwords_df.values
adjmat_path = r"data/glove_data/adjmat.bin"
with open(adjmat_path, 'wb') as fo:
    pickle.dump(adjmat, fo)

adjmat_path = r"data/glove_data/adjmat.bin"
bin_file = open(adjmat_path, "rb")
adjmat = pickle.load(bin_file)
bin_file.close()
print("adjmat: ", adjmat.shape, adjmat)

adjmat:  (45, 45) [[0. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]]


In [27]:
adjmat_2d = embedding.fit_transform(adjmat)

plt.figure(figsize=(15, 15))

i = 0
for index, row in wordsXwords_df.iterrows():
    
    color = 'r'
    if i >= len(objects):
        color = 'b'
        
    plt.scatter(adjmat_2d[i][0], adjmat_2d[i][1], c=color, edgecolor='k', s=100, label=index)
    plt.annotate(
        index,
        xy=(adjmat_2d[i][0], adjmat_2d[i][1]),
        xytext=(-14, 14),
        textcoords='offset points',
        bbox=dict(boxstyle='round,pad=0.5', fc='yellow', alpha=0.5),
        arrowprops=dict(arrowstyle = '->', connectionstyle='arc3,rad=0')
    )
    
    i += 1

legend_elements = []
legend_elements.append(plt.Rectangle((0, 0), 1, 1, color='r', label="Objects"))
legend_elements.append(plt.Rectangle((0, 0), 1, 1, color='b', label="Regions"))
plt.legend(handles=legend_elements, fontsize=11, bbox_to_anchor=(1, 1))
plt.axis('equal')

if isinstance(embedding, Isomap):
    plt.savefig(r"data/glove_data/2D_adjmat_Isomap.png", bbox_inches='tight', dpi=100)
elif isinstance(embedding, PCA):
    plt.savefig(r"data/glove_data/2D_adjmat_PCA.png", bbox_inches='tight', dpi=100)
elif isinstance(embedding, TSNE):
    plt.savefig(r"data/glove_data/2D_adjmat_TSNE.png", bbox_inches='tight', dpi=100)
plt.close()